name: todos_repository

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.0.0
  equatable: ^1.2.5
  firebase_core: ^1.1.0
  rxdart: ^0.24.0
